version: "3.9"

services:
  server:
    build: ./server
    container_name: studygram_server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: studygram_frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
    depends_on:
      - server
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: studygram_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
